typography_spectrum: 0.7201582631096244
color:
  brandColors:
    - '#0c0d12'
    - '#b7b0a6'
    - '#877a6a'
    - '#5d4539'
    - '#fee6e6'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.35806514229625463
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.31240392476320267
analytics:
  google: null
  facebook: null
  twitter: null
name: PhilipNelson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 64b7b447-d796-4740-8ea2-5caa064736c3
    type: content
  - name: Schedule
    id: a877caef-c6b9-401a-8094-9c8c79219e71
    type: content
  - name: Demos
    id: 1233515d-9263-474c-ac94-25818dede2ee
    type: content
  - name: Distilled Song List
    id: e0ae5482-b16f-4370-91ff-c5da0c1b9858
    type: content
  - name: Our House Concerts
    id: 49855f10-0f96-4ac5-960d-14854a33baad
    type: content
favicon: null
title: Philip Nelson and Distilled Spirits
purpose: []
