name: PhilipNelson
favicon: null
layout_spectrum: 0.05189
typography_spectrum: 0.36241
title: Philip Nelson and Distilled Spirits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0d12'
    - '#b7b0a6'
    - '#877a6a'
    - '#5d4539'
    - '#fee6e6'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.35806514229625463
  rhythmicContrast: 0.5
purpose: []
