name: PhilipNelson
favicon: null
layout_spectrum: 0.09816
typography_spectrum: 0.4486285562161356
title: Philip Nelson and Distilled Spirits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0d12'
    - '#b7b0a6'
    - '#877a6a'
    - '#5d4539'
    - '#fee6e6'
  brandStrength: 0.7308760497253388
  lightness: 0.75
  saturation: 0.35806514229625463
  rhythmicContrast: 0.75
purpose: []
