typography_spectrum: 0.36241
color:
  brandColors:
    - '#0c0d12'
    - '#b7b0a6'
    - '#877a6a'
    - '#5d4539'
    - '#fee6e6'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.35806514229625463
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05189
analytics:
  google: null
  facebook: null
  twitter: null
name: PhilipNelson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 64b7b447-d796-4740-8ea2-5caa064736c3
    type: content
favicon: null
title: Philip Nelson and Distilled Spirits
purpose: []
